[package]
name = "dalybms"
version = "0.1.0"
edition = "2021"

[lib]
name = "dalybms_lib"
path = "src/lib.rs"

[[bin]]
name = "dalybms"
path = "src/main.rs"
required-features = ["bin-dependencies"]

[features]
default = ["bin-dependencies"]
bin-dependencies = [
    "dep:anyhow",
    "dep:log",
    "clap/derive",
    "dep:clap-verbosity-flag",
    "dep:clap-num",
    "dep:humantime",
    "dep:flexi_logger",
]

[dependencies]
serialport = "4"
# Requirements for bin
anyhow = { version = "1", optional = true }
log = { version = "0.4", optional = true }
clap = { version = "4", optional = true }
clap-verbosity-flag = { version = "2", optional = true }
clap-num = { version = "1", optional = true }
humantime = { version = "2", optional = true }
flexi_logger = { version = "0.27", optional = true }
