[package]
name = "dalybms"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/acpiccolo/Daly-BMS"
description = "Daly BMS protocol and commandline tool"

[lib]
name = "dalybms_lib"
path = "src/lib.rs"

[[bin]]
name = "dalybms"
path = "src/main.rs"
required-features = ["bin-dependencies"]

[features]
default = ["bin-dependencies"] # Removed serde = ["dep:serde"]
serialport = ["dep:serialport"]
tokio-serial-async = ["dep:tokio-serial", "tokio/time", "tokio/io-util"]
protocol_serde = [] # Feature for enabling serde in the library part

bin-dependencies = [
    "dep:anyhow",
    "serialport", # This enables the 'serialport' feature for the library
    "protocol_serde", # This enables the 'protocol_serde' feature for the library
    "clap/derive",
    "dep:clap-verbosity-flag",
    "dep:clap-num",
    "dep:humantime",
    "dep:flexi_logger",
    "dep:chrono",
    "dep:rumqttc",
    "dep:serde_yaml",
    "dep:rand",
    "dep:serde_json",
]

[dependencies]
thiserror = "2"
log = { version = "0.4" }
serde = { version = "1", features = ["derive"] } # No longer optional
serde_yaml = { version = "0.9", optional = true }
rumqttc = { version = "0.22.0", optional = true } # No explicit features
serialport = { version = "4", optional = true }
tokio-serial = { version = "5", optional = true }
tokio = { version = "1", default-features = false, optional = true }
# Requirements for bin
anyhow = { version = "1", optional = true }
clap = { version = "4", optional = true }
clap-verbosity-flag = { version = "3", optional = true }
clap-num = { version = "1", optional = true }
humantime = { version = "2", optional = true }
flexi_logger = { version = "0.29.0", optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
rand = { version = "0.8", optional = true }
serde_json = { version = "1.0", optional = true }
# Note: rumqttc and serde_yaml are already added above with optional = true

[package.metadata.cargo-machete]
ignored = ["clap-num"]

[dev-dependencies]
tempfile = "3"
